services:
  fleetmanager-api:
    build:
       context: FleetManager.API
       dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mssql-db

  mssql-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-container
    environment:
      SA_PASSWORD: "StrongPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
